{{- if not .Values.useExistingSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "updater.fullname" . }}
type: Opaque
data:
  SIGNER_PRIVATE_KEY: {{ .Values.secrets.signerPrivateKey | b64enc }}
  SENDER_PRIVATE_KEY: {{ .Values.secrets.senderPrivateKey | b64enc }}
{{- end }}