apiVersion: v1
kind: Service
metadata:
  name: {{include "updater.fullname" .}}
  labels: {{- include "updater.labels" . | nindent 4}}
spec:
  type: ClusterIP
  ports:
    - port: 4014
      targetPort: http-prometheus
      protocol: TCP
      name: http-prometheus
  selector: {{- include "updater.selectorLabels" . | nindent 4}}
