[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]

[etherscan]
gravity_testnet = { key = "", chain = "13505", url = "https://explorer-sepolia.gravity.xyz/api" }
anvil = { key = "", chain = "31337", url = "http://127.0.0.1:8545" }
